[2024-11-05T00:49:46.749-0300] {processor.py:186} INFO - Started process (PID=5800) to work on /home/lucaires/anaconda3/envs/venv_airflow/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-05T00:49:46.749-0300] {processor.py:914} INFO - Processing file /home/lucaires/anaconda3/envs/venv_airflow/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-05T00:49:46.751-0300] {logging_mixin.py:190} INFO - [2024-11-05T00:49:46.751-0300] {dagbag.py:588} INFO - Filling up the DagBag from /home/lucaires/anaconda3/envs/venv_airflow/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-05T00:49:46.753-0300] {logging_mixin.py:190} INFO - [2024-11-05T00:49:46.753-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucaires/anaconda3/envs/venv_airflow/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-05T00:49:46.754-0300] {logging_mixin.py:190} INFO - [2024-11-05T00:49:46.754-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-05T00:49:46.754-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/lucaires/anaconda3/envs/venv_airflow/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-05T00:49:46.763-0300] {processor.py:208} INFO - Processing /home/lucaires/anaconda3/envs/venv_airflow/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-11-05T00:50:46.589-0300] {processor.py:186} INFO - Started process (PID=6622) to work on /home/lucaires/anaconda3/envs/venv_airflow/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-05T00:50:46.593-0300] {processor.py:914} INFO - Processing file /home/lucaires/anaconda3/envs/venv_airflow/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-05T00:50:46.595-0300] {logging_mixin.py:190} INFO - [2024-11-05T00:50:46.595-0300] {dagbag.py:588} INFO - Filling up the DagBag from /home/lucaires/anaconda3/envs/venv_airflow/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-05T00:50:46.597-0300] {logging_mixin.py:190} INFO - [2024-11-05T00:50:46.597-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucaires/anaconda3/envs/venv_airflow/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-05T00:50:46.597-0300] {logging_mixin.py:190} INFO - [2024-11-05T00:50:46.597-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-05T00:50:46.598-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/lucaires/anaconda3/envs/venv_airflow/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-05T00:50:46.607-0300] {processor.py:208} INFO - Processing /home/lucaires/anaconda3/envs/venv_airflow/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
